import Head from "next/head";
import Image from "next/image";

import { FiMail } from "react-icons/fi";
import { HiOutlineLockClosed } from "react-icons/hi";
import { FaUserAlt } from "react-icons/fa";

import { useState } from "react";
import axios from "axios";
import { setUserSession } from "./utils/session";

import { redirect } from "next/navigation";

export default function Home() {
  const [login, setLogin] = useState("");
  const [pwd, setPwd] = useState("");

  const handleLogin = () => {
    axios
      .post(`http://localhost:4000/login`, { login, pwd })
      .then((response) => {
        if (response.data.auth) {
          setUserSession(response.data.token);
          redirect("/HomePage");
        } else {
          setUserSession(response.data.token);
        }
      })
      .catch((error) => {
        console.log(error);
      });
  };
  return (
    <>
      <Head>
        <title>LoginPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>.</style>
      </Head>
      <main>
        <div className="w-full h-screen overflow-hidden flex justify-center items-center bg-gradient-to-tr from-cyan-400 to-fuchsia-500">
          <div className="flex bg-white rounded-lg p-10 flex-col justify-center items-start gap-5 mx-5">
            {/* title and icon */}
            <h1 className=" font-bold flex flex-col items-center justify-center mb-12 mt-8 w-full gap-6">
              <FaUserAlt className="text-5xl text-gray-800" />
              <p className="text-3xl font-bold text-gray-800">Login</p>
            </h1>

            {/* email */}
            <div className="w-full flex items-center gap-3 bg-[#d7daff] px-6 rounded-xl">
              <FiMail className=" text-gray-500 text-xl cursor-pointer" />
              <input
                id="email"
                type="email"
                placeholder="Enter Email"
                className=" py-2 pl-3 bg-[#d7daff] outline-none w-[90%] placeholder-gray-500"
                onChange={(e) => setLogin(e.target.value)}
              />
            </div>
            {/* password */}
            <div className="w-full flex items-center gap-3 bg-[#d7daff] px-6 rounded-xl">
              <HiOutlineLockClosed className=" text-gray-500 text-xl cursor-pointer" />
              <input
                id="password"
                type="password"
                placeholder="Enter Password"
                className=" py-2 pl-3 bg-[#d7daff] outline-none w-[90%] placeholder-gray-500"
                onChange={(e) => setPwd(e.target.value)}
              />
            </div>
            {/* sign in */}
            <input
              type="submit"
              value="SIGN IN"
              id="submitBtn"
              className="w-full p-2 text-white bg-gray-800 rounded-xl hover:bg-opacity-90 transition-all cursor-pointer active:cursor-progress"
              onClick={handleLogin}
            />
          </div>
        </div>
      </main>
    </>
  );
}
